// MCC (Merchant Category Code) reference data
export const MCC_CODES: { code: string; label: string }[] = [
  { code: '0742', label: 'Veterinary Services' },
  { code: '0763', label: 'Agricultural Cooperative' },
  { code: '1520', label: 'General Contractors' },
  { code: '1711', label: 'Heating, Plumbing, A/C' },
  { code: '1731', label: 'Electrical Contractors' },
  { code: '1799', label: 'Special Trade Contractors' },
  { code: '2741', label: 'Miscellaneous Publishing' },
  { code: '2842', label: 'Specialty Cleaning' },
  { code: '4011', label: 'Railroads' },
  { code: '4111', label: 'Transportation — Suburban' },
  { code: '4112', label: 'Passenger Railways' },
  { code: '4121', label: 'Taxicabs/Rideshares' },
  { code: '4131', label: 'Bus Lines' },
  { code: '4214', label: 'Motor Freight Carriers & Trucking' },
  { code: '4215', label: 'Courier Services' },
  { code: '4411', label: 'Cruise Lines' },
  { code: '4511', label: 'Airlines, Air Carriers' },
  { code: '4582', label: 'Airports, Airport Terminals' },
  { code: '4722', label: 'Travel Agencies, Tour Operators' },
  { code: '4784', label: 'Tolls/Bridge Fees' },
  { code: '4789', label: 'Transportation Services' },
  { code: '4812', label: 'Telecommunication Equipment' },
  { code: '4814', label: 'Telecommunication Services' },
  { code: '4816', label: 'Computer Network Services' },
  { code: '4899', label: 'Cable, Satellite, Pay Television' },
  { code: '4900', label: 'Utilities' },
  { code: '5013', label: 'Motor Vehicle Supplies' },
  { code: '5021', label: 'Office & Commercial Furniture' },
  { code: '5039', label: 'Construction Materials' },
  { code: '5044', label: 'Photographic Equipment' },
  { code: '5045', label: 'Computers & Peripherals' },
  { code: '5047', label: 'Medical & Dental Equipment' },
  { code: '5065', label: 'Electronic Parts & Equipment' },
  { code: '5072', label: 'Hardware Equipment & Supplies' },
  { code: '5074', label: 'Plumbing & Heating Equipment' },
  { code: '5085', label: 'Industrial Supplies' },
  { code: '5094', label: 'Precious Stones & Metals' },
  { code: '5099', label: 'Durable Goods' },
  { code: '5111', label: 'Stationery & Office Supplies' },
  { code: '5122', label: 'Drugs, Drug Proprietaries' },
  { code: '5131', label: 'Piece Goods & Textiles' },
  { code: '5137', label: 'Uniforms & Commercial Clothing' },
  { code: '5139', label: 'Commercial Footwear' },
  { code: '5169', label: 'Chemicals & Allied Products' },
  { code: '5172', label: 'Petroleum & Petroleum Products' },
  { code: '5192', label: 'Books, Periodicals, Newspapers' },
  { code: '5193', label: 'Florists Supplies & Nursery Stock' },
  { code: '5199', label: 'Nondurable Goods' },
  { code: '5200', label: 'Home Supply Warehouse Stores' },
  { code: '5211', label: 'Building Materials & Lumber' },
  { code: '5231', label: 'Glass, Paint, Wallpaper' },
  { code: '5251', label: 'Hardware Stores' },
  { code: '5261', label: 'Nurseries & Garden Supply' },
  { code: '5271', label: 'Mobile Home Dealers' },
  { code: '5300', label: 'Wholesale Clubs' },
  { code: '5309', label: 'Duty Free Stores' },
  { code: '5310', label: 'Discount Stores' },
  { code: '5311', label: 'Department Stores' },
  { code: '5331', label: 'Variety Stores' },
  { code: '5399', label: 'General Merchandise' },
  { code: '5411', label: 'Grocery Stores, Supermarkets' },
  { code: '5422', label: 'Freezer & Locker Meat' },
  { code: '5441', label: 'Candy, Nut, Confectionery' },
  { code: '5451', label: 'Dairy Products Stores' },
  { code: '5462', label: 'Bakeries' },
  { code: '5499', label: 'Misc Food Stores' },
  { code: '5511', label: 'Car & Truck Dealers (New & Used)' },
  { code: '5521', label: 'Car & Truck Dealers (Used Only)' },
  { code: '5531', label: 'Auto & Home Supply Stores' },
  { code: '5532', label: 'Automotive Tire Stores' },
  { code: '5533', label: 'Automotive Parts & Accessories' },
  { code: '5541', label: 'Service Stations' },
  { code: '5551', label: 'Boat Dealers' },
  { code: '5571', label: 'Motorcycle Shops & Dealers' },
  { code: '5599', label: 'Misc Auto Dealers' },
  { code: '5611', label: 'Men\'s & Boys\' Clothing' },
  { code: '5621', label: 'Women\'s Ready-to-Wear' },
  { code: '5631', label: 'Women\'s Accessory & Specialty' },
  { code: '5641', label: 'Children\'s & Infants\' Wear' },
  { code: '5651', label: 'Family Clothing Stores' },
  { code: '5655', label: 'Sports & Riding Apparel' },
  { code: '5661', label: 'Shoe Stores' },
  { code: '5691', label: 'Clothing Stores' },
  { code: '5697', label: 'Tailors, Alterations' },
  { code: '5698', label: 'Wig & Toupee Stores' },
  { code: '5699', label: 'Misc Apparel & Accessories' },
  { code: '5712', label: 'Furniture, Home Furnishings' },
  { code: '5713', label: 'Floor Covering Stores' },
  { code: '5714', label: 'Drapery & Upholstery' },
  { code: '5718', label: 'Fireplace & Accessories' },
  { code: '5719', label: 'Misc Home Furnishing' },
  { code: '5722', label: 'Household Appliance Stores' },
  { code: '5732', label: 'Electronics Stores' },
  { code: '5733', label: 'Music Stores & Instruments' },
  { code: '5734', label: 'Computer Software Stores' },
  { code: '5735', label: 'Record Stores' },
  { code: '5812', label: 'Eating Places, Restaurants' },
  { code: '5813', label: 'Bars, Cocktail Lounges' },
  { code: '5814', label: 'Fast Food Restaurants' },
  { code: '5912', label: 'Drug Stores & Pharmacies' },
  { code: '5921', label: 'Package Stores — Beer, Wine' },
  { code: '5931', label: 'Used Merchandise & Secondhand' },
  { code: '5932', label: 'Antique Shops' },
  { code: '5933', label: 'Pawn Shops' },
  { code: '5935', label: 'Wrecking & Salvage Yards' },
  { code: '5940', label: 'Bicycle Shops' },
  { code: '5941', label: 'Sporting Goods Stores' },
  { code: '5942', label: 'Book Stores' },
  { code: '5943', label: 'Stationery Stores' },
  { code: '5944', label: 'Jewelry Stores' },
  { code: '5945', label: 'Hobby, Toy & Game Shops' },
  { code: '5946', label: 'Camera & Photographic Supply' },
  { code: '5947', label: 'Gift, Card, Novelty Stores' },
  { code: '5948', label: 'Luggage & Leather Goods' },
  { code: '5949', label: 'Sewing & Fabric Stores' },
  { code: '5950', label: 'Glassware & Crystal Stores' },
  { code: '5960', label: 'Direct Marketing — Insurance' },
  { code: '5962', label: 'Direct Marketing — Travel' },
  { code: '5963', label: 'Door-To-Door Sales' },
  { code: '5964', label: 'Direct Marketing — Catalog' },
  { code: '5965', label: 'Direct Marketing — Combo Catalog & Retail' },
  { code: '5966', label: 'Direct Marketing — Outbound Telemarketing' },
  { code: '5967', label: 'Direct Marketing — Inbound Teleservices' },
  { code: '5968', label: 'Direct Marketing — Subscription' },
  { code: '5969', label: 'Direct Marketing — Other' },
  { code: '5970', label: 'Artist\'s Supply & Craft Shops' },
  { code: '5971', label: 'Art Dealers & Galleries' },
  { code: '5972', label: 'Stamp & Coin Stores' },
  { code: '5973', label: 'Religious Goods Stores' },
  { code: '5977', label: 'Cosmetic Stores' },
  { code: '5978', label: 'Typewriter Stores' },
  { code: '5983', label: 'Fuel Dealers' },
  { code: '5992', label: 'Florists' },
  { code: '5993', label: 'Cigar Stores & Stands' },
  { code: '5994', label: 'News Dealers & Newsstands' },
  { code: '5995', label: 'Pet Shops & Pet Food' },
  { code: '5996', label: 'Swimming Pools' },
  { code: '5997', label: 'Electric Razor Stores' },
  { code: '5998', label: 'Tent & Awning Shops' },
  { code: '5999', label: 'Miscellaneous & Specialty Retail' },
  { code: '6010', label: 'Financial Institutions — Manual Cash' },
  { code: '6011', label: 'Financial Institutions — ATM' },
  { code: '6012', label: 'Financial Institutions — Merchandise & Services' },
  { code: '6051', label: 'Non-FI Foreign Currency, Money Orders' },
  { code: '6211', label: 'Security Brokers/Dealers' },
  { code: '6300', label: 'Insurance Underwriting' },
  { code: '6513', label: 'Real Estate Agents & Managers' },
  { code: '7011', label: 'Hotels, Motels, Resorts' },
  { code: '7012', label: 'Timeshares' },
  { code: '7032', label: 'Sporting & Recreational Camps' },
  { code: '7033', label: 'Trailer Parks & Campgrounds' },
  { code: '7210', label: 'Laundry, Cleaning, Garment Services' },
  { code: '7211', label: 'Laundries — Family & Commercial' },
  { code: '7216', label: 'Dry Cleaners' },
  { code: '7217', label: 'Carpet & Upholstery Cleaning' },
  { code: '7221', label: 'Photographic Studios' },
  { code: '7230', label: 'Barber & Beauty Shops' },
  { code: '7251', label: 'Shoe Repair/Hat Cleaning' },
  { code: '7261', label: 'Funeral Services & Crematories' },
  { code: '7273', label: 'Dating/Escort Services' },
  { code: '7276', label: 'Tax Preparation Services' },
  { code: '7277', label: 'Counseling Services' },
  { code: '7278', label: 'Buying/Shopping Services' },
  { code: '7296', label: 'Clothing Rental' },
  { code: '7297', label: 'Massage Parlors' },
  { code: '7298', label: 'Health & Beauty Spas' },
  { code: '7299', label: 'Miscellaneous Personal Services' },
  { code: '7311', label: 'Advertising Services' },
  { code: '7321', label: 'Consumer Credit Reporting' },
  { code: '7333', label: 'Commercial Photography & Art' },
  { code: '7338', label: 'Quick Copy & Reproduction' },
  { code: '7339', label: 'Stenographic & Secretarial' },
  { code: '7342', label: 'Exterminating Services' },
  { code: '7349', label: 'Cleaning & Maintenance' },
  { code: '7361', label: 'Employment Agencies & Temp Help' },
  { code: '7372', label: 'Computer Programming, Data Processing' },
  { code: '7375', label: 'Information Retrieval Services' },
  { code: '7379', label: 'Computer Repair' },
  { code: '7392', label: 'Consulting & PR Services' },
  { code: '7393', label: 'Detective & Protective Agencies' },
  { code: '7394', label: 'Equipment Rental & Leasing' },
  { code: '7395', label: 'Photo Developing' },
  { code: '7399', label: 'Miscellaneous Business Services' },
  { code: '7511', label: 'Truck Stop' },
  { code: '7512', label: 'Car Rental Agencies' },
  { code: '7513', label: 'Truck/Utility Trailer Rental' },
  { code: '7519', label: 'Recreational Vehicle Rentals' },
  { code: '7523', label: 'Parking Lots, Garages' },
  { code: '7531', label: 'Auto Body Repair Shops' },
  { code: '7534', label: 'Tire Re-treading & Repair' },
  { code: '7535', label: 'Automotive Paint Shops' },
  { code: '7538', label: 'Automotive Service Shops' },
  { code: '7542', label: 'Car Washes' },
  { code: '7549', label: 'Towing Services' },
  { code: '7622', label: 'Electronics Repair' },
  { code: '7623', label: 'A/C, Refrigeration Repair' },
  { code: '7629', label: 'Electrical & Small Appliance Repair' },
  { code: '7631', label: 'Watch, Clock & Jewelry Repair' },
  { code: '7641', label: 'Furniture Repair & Refinishing' },
  { code: '7692', label: 'Welding Repair' },
  { code: '7699', label: 'Miscellaneous Repair Shops' },
  { code: '7800', label: 'Government-Owned Lotteries' },
  { code: '7801', label: 'Government-Licensed Online Casinos' },
  { code: '7802', label: 'Government-Licensed Horse/Dog Racing' },
  { code: '7829', label: 'Motion Picture Distribution' },
  { code: '7832', label: 'Motion Picture Theaters' },
  { code: '7841', label: 'Video Tape Rental Stores' },
  { code: '7911', label: 'Dance Halls & Studios' },
  { code: '7922', label: 'Theatrical Ticket Agencies' },
  { code: '7929', label: 'Bands, Orchestras, Entertainers' },
  { code: '7932', label: 'Billiard & Pool Establishments' },
  { code: '7933', label: 'Bowling Alleys' },
  { code: '7941', label: 'Athletic Fields, Commercial Sports' },
  { code: '7991', label: 'Tourist Attractions & Exhibits' },
  { code: '7992', label: 'Golf Courses — Public' },
  { code: '7993', label: 'Video Amusement Game Supplies' },
  { code: '7994', label: 'Video Game Arcades' },
  { code: '7995', label: 'Betting/Casino Gambling' },
  { code: '7996', label: 'Amusement Parks, Circuses' },
  { code: '7997', label: 'Membership Clubs & Spas' },
  { code: '7998', label: 'Aquariums' },
  { code: '7999', label: 'Recreation Services' },
  { code: '8011', label: 'Doctors' },
  { code: '8021', label: 'Dentists, Orthodontists' },
  { code: '8031', label: 'Osteopaths' },
  { code: '8041', label: 'Chiropractors' },
  { code: '8042', label: 'Optometrists, Ophthalmologists' },
  { code: '8043', label: 'Opticians & Optical Goods' },
  { code: '8049', label: 'Podiatrists, Chiropodists' },
  { code: '8050', label: 'Nursing & Personal Care Facilities' },
  { code: '8062', label: 'Hospitals' },
  { code: '8071', label: 'Medical & Dental Labs' },
  { code: '8099', label: 'Health Services' },
  { code: '8111', label: 'Legal Services, Attorneys' },
  { code: '8211', label: 'Schools, Elementary & Secondary' },
  { code: '8220', label: 'Colleges & Universities' },
  { code: '8241', label: 'Correspondence Schools' },
  { code: '8244', label: 'Business & Secretarial Schools' },
  { code: '8249', label: 'Vocational & Trade Schools' },
  { code: '8299', label: 'Schools & Educational Services' },
  { code: '8351', label: 'Child Care Services' },
  { code: '8398', label: 'Charitable & Social Service Organizations' },
  { code: '8641', label: 'Civic, Social, Fraternal Associations' },
  { code: '8651', label: 'Political Organizations' },
  { code: '8661', label: 'Religious Organizations' },
  { code: '8675', label: 'Automobile Associations' },
  { code: '8699', label: 'Membership Organizations' },
  { code: '8734', label: 'Testing Laboratories' },
  { code: '8911', label: 'Architectural, Engineering, Surveying' },
  { code: '8931', label: 'Accounting, Auditing, Bookkeeping' },
  { code: '8999', label: 'Professional Services' },
  { code: '9211', label: 'Court Costs, Fines' },
  { code: '9222', label: 'Fines' },
  { code: '9223', label: 'Bail & Bond Payments' },
  { code: '9311', label: 'Tax Payments' },
  { code: '9399', label: 'Government Services' },
  { code: '9402', label: 'Postal Services — Government' },
  { code: '9405', label: 'Intra-Government Purchases' },
]

// Country reference data (ISO 3166-1)
export const COUNTRIES: string[] = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
  'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
  'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
  'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
  'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
  'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
  'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile',
  'China', 'Colombia', 'Comoros', 'Congo (DRC)', 'Congo (Republic)',
  'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
  'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
  'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
  'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
  'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
  'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
  'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland',
  'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
  'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
  'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
  'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
  'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
  'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali',
  'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
  'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
  'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru',
  'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger',
  'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman',
  'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea',
  'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis',
  'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe',
  'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone',
  'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
  'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
  'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
  'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste',
  'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
  'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
  'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu',
  'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe',
]

// Business Activities from Store Onboarding API
export const BUSINESS_ACTIVITIES: string[] = [
  'Accounting, Tax Preparation, and Management Consulting',
  'Advertising, Marketing and PR',
  'Aerospace, Airline, Airport, Sea Port and Terminal Operations',
  'Agriculture, Fishing, Forestry, and Logging',
  'Alcoholic Beverages, Beer, Wine and Liquor Stores',
  'Amusement Parks and Attractions, Hotels and Resorts',
  'Apparel, Accessories, Clothing and Shoe Stores',
  'Architecture, Engineering and Design',
  'Auctions',
  'Automobile and related activities',
  'Banking, Financial Services, and Investment',
  'Biotechnology',
  'Brokerage',
  'Call Centers',
  'Chemicals and Petrochemicals',
  'Construction, Building Materials, and Equipment',
  'Consumer Electronics, Parts and Repair',
  'Data and Records Management',
  'Defense and related activities',
  'Department Stores',
  'E-Commerce and Fintech',
  'Education (Schools, Colleges, Universities)',
  'Energy, Oil and Gas',
  'Facilities Management and Parking',
  'Food and Dairy Product Manufacturing and Packaging',
  'Funeral Homes and Services',
  'General Trading',
  'Grocery',
  'Healthcare and Medical Services (Clinics, Labs, Hospitals)',
  'HR, Payroll and Recruiting Services',
  'Insurance and Risk Management',
  'IT Hardware, Networking, and Electronic Equipment',
  'Jewelry and Precious Metal',
  'Laundry and Dry Cleaning',
  'Legal Practice',
  'Libraries, Archives and Museums',
  'Machinery and Equipment',
  'Manufacturing',
  'Medical Devices, Supplies and Equipment',
  'Metal, Mineral, Mining and Quarrying',
  'Motion Picture, Music, and Media Production',
  'Newspaper Publishers',
  'Payment Service Providers and Related Services',
  'Performing Arts',
  'Property Leasing and Management',
  'Radio, Television Broadcasting',
  'Real Estate',
  'Religious Organizations',
  'Rental Cars',
  'Restaurants and Bars',
  'Retail Trade and Services',
  'Semiconductor and Microchip Manufacturing',
  'Sewage Treatment, Waste Management and Recycling',
  'Social and Membership Organizations',
  'Software Development',
  'Telecommunications and Equipment',
  'Textiles',
  'Tobacco',
  'Transportation, Taxi, Buses, Trucking and Transit Systems',
  'Travel Agents and Services',
  'Trust, Fiduciary and Custody Activities',
  'Used Cars',
  'Veterinary Clinics and Services',
  'Warehousing and Storage',
  'Water Treatment and Utilities',
  'Wholesale and Distribution',
  'Others',
]

// Settlement frequencies
export const SETTLEMENT_FREQUENCIES: string[] = [
  'Daily',
  'Weekly',
  'Bi-Weekly',
  'Monthly',
]

// Currencies
export const CURRENCIES: string[] = [
  'AED', 'USD', 'EUR', 'GBP', 'SAR', 'QAR', 'BHD', 'KWD', 'OMR', 'INR',
]

// Store types
export const STORE_TYPES: { value: string; label: string }[] = [
  { value: 'soleTrader', label: 'Sole Trader' },
  { value: 'registeredBusiness', label: 'Registered Business' },
]

// Document types for upload (aligned with Store Onboarding API)
export const DOC_TYPES = [
  { key: 'trade_license',             label: 'Trade License',              icon: '📋', desc: 'Official trade/business license' },
  { key: 'memorandum_of_association', label: 'Memorandum of Association',  icon: '📜', desc: 'MOA or Articles of Association' },
  { key: 'utility_bill',             label: 'Utility Bill',               icon: '🏠', desc: 'Recent utility bill for address verification' },
  { key: 'tax',                      label: 'Tax Certificate',            icon: '🧾', desc: 'Tax registration certificate (TRN)' },
  { key: 'passport',                 label: 'Passport',                   icon: '🛂', desc: 'Valid passport of the business owner' },
  { key: 'visa',                     label: 'Visa',                       icon: '✈️', desc: 'Current visa if applicable' },
  { key: 'identity_document',        label: 'Emirates ID',                icon: '🪪', desc: 'National ID or Emirates ID' },
  { key: 'bank_statement',           label: 'Bank Statement',             icon: '🏦', desc: 'Recent bank statement' },
  { key: 'business_documents',       label: 'Other Business Documents',   icon: '🗂️', desc: 'Additional business documentation' },
  { key: 'other',                    label: 'Other',                      icon: '📎', desc: 'Any other supporting documents' },
]

// Identity types for owners
export const IDENTITY_TYPES: { value: string; label: string }[] = [
  { value: 'emiratesId', label: 'Emirates ID' },
  { value: 'passport', label: 'Passport' },
  { value: 'tradeLicense', label: 'Trade License' },
]
